### ISSUE TITLE
When is the next scheduled release?

### ISSUE THREAD

**Issue by Walliee** [postmanlabs/swagger2-postman2#11]
Great job on this library!

https://github.com/postmanlabs/swagger2-postman2/commit/ed10a90a8facff088962a1063087d8283c4adb7e fixes 2 issues:
1) When a tree node has requestCount = 1 but no requests (child node has it).
2) Having a fallback when json-schema-faker is unable to handle a format.

I’d like to use this fix but cannot pull from GitHub - need it to be in NPM registry.
Any chance you could release a new version soon?

**Comment by zjrunner** [comment]
@abhijitpostman - any word on this?  I'm in the same boat.  Made fixes for the above locally only to realize you already had them in the repo.  I've got some other fixes I was going to log and contribute too, but if the project is dead for you I guess I'd fork and publish @scope.

**Comment by abhijitkane** [comment]
@zjrunner Apologies for the late response here. The updated converter was included in the latest Postman release. We're now using a combination of `swagger2openapi` and `openapi-to-postmanv2` for the conversion.
