### ISSUE TITLE
Use operationId where summary is missing

### ISSUE THREAD

**Issue by zjrunner** [postmanlabs/swagger2-postman2#19]
This could alternatively go to https://github.com/postmanlabs/postman-app-support/issues/4458, but a fix in the converter is also a simple conditional in helpers.js.  I have a change in a fork if acceptable.

```
    rName = operation.summary;

    if (!rName) {
      rName = operation.operationId;
    }
```

**Comment by jdrews** [comment]
👍  Please merge this in!

**Comment by zjrunner** [comment]
sounds like the main app is fixed according to the linked issue!  I haven't tested it out yet, but if true and it handles the case here fully this could be closed along with the PR.
