### ISSUE TITLE
Import OpenApi: issue with multiple "_" in host variable

### ISSUE THREAD

**Issue by koying** [postmanlabs/swagger2-postman2#30]
**Describe the bug**
When importing a json openapi spec with multiple "_" in a variable name as "host", the generated urls are wrong.

**To Reproduce**
1. Use PetStore openapi spec
2. Change `"host": "petstore.swagger.io",` to  `"host":"{{petstore_url_port}}",`
3. Import spec in postman
4. See that generated url are `https://{{petstore_url_portpostman_variable_close/_DB/v2/pet`

**Expected behavior**
Generated url are `https://{{petstore_url_port}}/v2/pet`

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0.9
 - OS: Win 10

**Additional context**
Using a variable name with a single "_", eg "{{petstore_url}}" works as expected

**Comment by abhijitkane** [comment]
@koying Can you check in the latest build (v7.3.2)?

**Comment by koying** [comment]
Works in 7.**2**.2.
Thanks
